@server = https://glowing-couscous-j4q5xwwpw257g5-8080.app.github.dev
###
GET {{server}}/api/marcas/2
###
POST {{server}}/api/marcas
Content-Type: application/json


{"nombre": "Motorla", "categoria": "electrodomestico", "descripcion": "Duracion de bateria extendida"}
###
GET {{server}}/api/productos
###
POST {{server}}/api/productos
Content-Type: application/json

{"nombre": "Juan"}
###
GET {{server}}/api/ventas
###
GET {{server}}/api/ventas/1
###
GET {{server}}/api/ventas/1/formacion
###
GET {{server}}/api/ingresos

